# Changes here will be overwritten by Copier
_commit: 0.1.16
_src_path: gh:12rambau/pypackage
author_email: pierrick.rambaud49@gmail.com
author_first_name: Pierrick
author_last_name: Rambaud
author_orcid: ""
creation_year: "2020"
github_repo_name: ipygee
github_user: 12rambau
project_name: ipygee
project_slug: ipygee
short_description: widgets to interact with GEE API
